### ISSUE TITLE
[Concept] :  [Saber] : Tip the Scale - Hungry Dragon Gaiden

### ISSUE THREAD

**Issue by slamjamuels** [KBVE/kbve#167]
Tip the Scale is a baby dragon with a big appetite. He's reached the base of Mount Marshmellow in search of snacks. At its peak is the Candy Kingdom, and the source of all that is delicious in this world, the AllMunch. Can Tip scale the mountain and seek his destiny? 

* * *

Tip the Scale is a working title for the 1month jam with the theme of [**Scale**]

Tip is a dragon, a scaled creature, that feasts, grows, and scales in size and strength. He'll have the opportunity to direct his diet and his growth, all the while scaling the mythical Mount Marshmellow to his ultimate goal; the Candy Kingdom. Candy minions can be eaten, immolated, and crushed without any true badfeel, because their souls return to the ALLMUNCH. The Candies are like Autobots, I guess. The Candy Kingdom will begin to send stronger soldiers to slow down Tip. Further, he may encounter other characters scaling the mountain as well.

* * *

**Alternative Examples/Sources**
Some references to consider are the Spyro the Dragon games, Ice Climbers, Rampage!. 

The Candy Kingdom is giving Transformers and Candyland the Board Game. There should be a dark candy conspiracy because what kingdom doesnt have a dark candy conspiracy?

* * *

**Additional information**
N/A, yet.

**Comment by h0lybyte** [comment]
I was thinking that the background / terrain starts as a forest-style basin and starts scaling into the mountain, As the player aka dragon is climbing up the forest/moutain, we alter the environment to slowly change into the candy-style mountain? Hmm just a though as of right now.

**Comment by ZombehCorp** [comment]
My thoughts on the general gameplay flow would be following a pathway up a cylindrical level, dealing with enemies or pick ups along the way.  The level would be made up of a "block" of the mountain, as shown in my attached images.  Utilizing a set up like that allows us to have a level start and end point driving transition into the next scene.  Each scene can consist of a unique appearance and atmosphere, slightly altering materials and lighting in order to reuse assets while giving them a fresh look for the new environment.  

This can keep the level spaces contained, easy to modify and set up new versions of it, and can help refine the scope of the game as needed.  It also is flexible enough to allow for different player interactions for the gameplay, as we haven't fully decided on the locomotion systems.  It could be real time, similar to Mario 64's Tall-Tall Mountain level as @h0lybyte pointed out, or it could be set up to work in the vein of a infinite runner with static positions and lateral movements.

![PlayerFlow](https://github.com/KBVE/kbve/assets/144863694/dbb8ab1f-543e-4659-8a4a-b98debf7b8b9)
![PlayerView](https://github.com/KBVE/kbve/assets/144863694/8ac7d4b7-7de6-4a71-8e04-d2c7d6fcd500)

**Comment by 1954764916** [comment]
**The order of playing the game is as follows：**

scene0--->scene1---->scene2

scene0：This scene contains scene options, game start and game end, and can also add other configurations and UI, and may be added to the list of all production staff

scene1 and scene2 as follows：See picture caption

 
 


<img width="923" alt="Scene1" src="https://github.com/KBVE/kbve/assets/112925197/d905535b-cdb3-4e5b-b399-45bae6864226">



<img width="1142" alt="Scene2" src="https://github.com/KBVE/kbve/assets/112925197/68c020b4-f591-4175-bde3-c68abea13de7">

Personally, I feel that the terrain area of ​​scene 1 is too large. Some elements can be appropriately deleted and added to scene 2. Both scenes need to add some new things, as you said, candies or enemies.and many other things.

Players can gain qualifications for growth through points (for example, getting bigger. I want to add some strange design techniques here: the player's dragon has no wings at the beginning, and only has wings when it grows up)

**Comment by h0lybyte** [comment]
I saw this earlier when I was looking through some of the concepts for the 2D/3D characters. 

This is just a reference/food for thought.

- [Video](https://www.youtube.com/watch?v=JvbsktWVHU8)
- [Repo](https://github.com/mixandjam/LBW-WallMerge/tree/master)
